server:
  port: 8762

spring:
  application:
    name: eureka-client-01

#  zipkin:
#    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/